version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "00:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    labels:
      - "deps"
    versioning-strategy: "increase"
    rebase-strategy: "disabled"
