name-template: "Draft 🌈"
prerelease: false
exclude-labels:
  - "skip-changelog"
  - "release"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "feat"
  - title: "🐛 Bug fixes"
    labels:
      - "fix"
  - title: "📖 Docs"
    labels:
      - "docs"
  - title: "📦 Dependencies"
    labels:
      - "deps"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## Changes
  $CHANGES
