name-template: 'Draft 🌈'
prerelease: false
exclude-labels:
  - 'skip-changelog'
  - 'release'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📖 Docs'
    labels:
      - 'docs'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## Changes
  $CHANGES
